In [ ]:
pip install spotipy

In [2]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd

In [3]:
cid = your_client_id
secret = your_client_secret
client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret)
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)
rihanna_uri = 'spotify:artist:5pKCCKE2ajJHZ9KAiaK11H?si=ZM9pI-KfTaOb5vE0VcbcdQ'

In [4]:
playlists = sp.user_playlists('yaneholandaa')
playlists_df = pd.DataFrame(playlists)
playlists_df.head()

playlist_name = []
playlist_tracks = []


for i, x in playlists_df['items'].items():
        playlist_name.append(x['name'])
        playlist_tracks.append(x['tracks']['total'])


my_playlists = pd.DataFrame({
    'name':playlist_name,
    'total tracks':playlist_tracks})
    
my_playlists

        name  total tracks
0    diamond           156
1  nacionais            32

In [5]:
#Searching for Rihanna's top tracks

top_tracks = sp.artist_top_tracks(rihanna_uri)

df = pd.DataFrame(top_tracks)
df.head()

track_id = []
track = []
duration = []
track_number = []

for i, x in df['tracks'].items():
        track.append(x['name'])
        duration.append(x['duration_ms'])
        track_number.append(x['track_number'])
        track_id.append(x['uri'])

df2 = pd.DataFrame({
    'track':track,
    'duration_ms':duration,
    'track_number':track_number,
    'track_id':track_id})
    
df2

,track,duration_ms,track_number,track_id
0,Umbrella,275986,1,spotify:track:2yPoXCs7BSIUrucMdK5PzV
1,Love On The Brain,224000,11,spotify:track:5oO3drDxtziYU2H1X23ZIp
2,This Is What You Came For,222160,1,spotify:track:0azC730Exh71aQlOt9Zj3y
3,Needed Me,191600,7,spotify:track:4pAl7FkDMNBsjykPXo91B3
4,Don't Stop The Music,267080,3,spotify:track:1Jo0Zg7XlrA6z0mFTZVdkn
5,Woo,235586,6,spotify:track:3HQcsqRjRdruUjkbDSgmVF
6,Only Girl (In The World),235493,5,spotify:track:2ENexcMEMsYk0rVJigVD3i
7,We Found Love,215226,3,spotify:track:6qn9YLKt13AGvpq9jfO8py
8,Disturbia,238626,13,spotify:track:2VOomzT6VavJOGBeySqaMc
9,FourFiveSeconds,188238,1,spotify:track:78TTtXnFQPzwqlbtbwqN0y

In [21]:
# Searching for Rihanna's albums
album = []
album_id = []
total_tracks = []


results = sp.artist_albums(rihanna_uri, album_type='album')

df_albums = pd.DataFrame(results)

for i, x in df_albums['items'].items():
        album.append(x['name'])
        album_id.append(x['uri'])
        total_tracks.append(x['total_tracks'])
     

df3 = pd.DataFrame({
    'album':album,
    'album_id':album_id,
    'total_tracks':total_tracks})

df3.insert(1, 'artist', 'Rihanna')
df3

,album,artist,album_id,total_tracks
0,ANTI (Deluxe),Rihanna,spotify:album:4UlGauD7ROb3YbVOFMgW5u,16
1,ANTI (Deluxe),Rihanna,spotify:album:4Q3ad90GtI0dxyE5ZishAS,16
2,ANTI,Rihanna,spotify:album:48i37aZTC1prDr4EcpQeEa,13
3,ANTI,Rihanna,spotify:album:3p39yDJtXkSw8QLMmB8yyD,13
4,Unapologetic (Deluxe Version),Rihanna,spotify:album:7yjQZX94GxVyqDTehxBejk,17
5,Unapologetic (Deluxe Version),Rihanna,spotify:album:4HsLpiXxuq5kxvMEALLyrh,17
6,Unapologetic (Deluxe),Rihanna,spotify:album:4eddbruVtOqw8khwxSH6H2,17
7,Unapologetic (Deluxe),Rihanna,spotify:album:5pLlGJrxuQO3jMoQe1XxZY,17
8,Unapologetic,Rihanna,spotify:album:0XJya16l3K1J2dEwY19F8z,14
9,Unapologetic,Rihanna,spotify:album:4XBfFj0WYyh5mBtU61EdyY,14
10,Unapologetic (Deluxe),Rihanna,spotify:album:1ciAVKFdlpLi2eGDlXv6Bo,17
11,Unapologetic (Edited Version),Rihanna,spotify:album:5UDXzVwWnn3mDy3mTpQPYb,14
12,Talk That Talk (Deluxe),Rihanna,spotify:album:3sW7wD2qdMjs7KncaOoIJ5,14
13,Talk That Talk (Deluxe),Rihanna,spotify:album:51h0awzHny8CZmIS6ECabP,14
14,Unapologetic (Deluxe Version [Edited]),Rihanna,spotify:album:0fuYENc2V5OhrMxu7VxRRr,17
15,Unapologetic (Standard Version [Edited]),Rihanna,spotify:album:023AUStvFJD8IzQqFeXRjB,14
16,Unapologetic (Edited Version),Rihanna,spotify:album:0T23GvNaBUGtMKxZko8LQG,14
17,Talk That Talk,Rihanna,spotify:album:1Kw1bVd07oRqcjrcjQKC8T,11
18,Talk That Talk,Rihanna,spotify:album:2g1EakEaW7fPTZC6vBmBCn,11
19,Talk That Talk (Deluxe Explicit),Rihanna,spotify:album:3oQebIVUPY0IPiROZSIQFl,14

In [8]:
#Return only album's uris and name

albums_uris = df3['album_id']
df_albums_uris = albums_uris.values.tolist()
print(df_albums_uris)

albums_names = df3['album']

df_albums_names = albums_names.values.tolist()
print(df_albums_names)

['spotify:album:4UlGauD7ROb3YbVOFMgW5u', 'spotify:album:4Q3ad90GtI0dxyE5ZishAS', 'spotify:album:48i37aZTC1prDr4EcpQeEa', 'spotify:album:3p39yDJtXkSw8QLMmB8yyD', 'spotify:album:7yjQZX94GxVyqDTehxBejk', 'spotify:album:4HsLpiXxuq5kxvMEALLyrh', 'spotify:album:4eddbruVtOqw8khwxSH6H2', 'spotify:album:5pLlGJrxuQO3jMoQe1XxZY', 'spotify:album:0XJya16l3K1J2dEwY19F8z', 'spotify:album:4XBfFj0WYyh5mBtU61EdyY', 'spotify:album:1ciAVKFdlpLi2eGDlXv6Bo', 'spotify:album:5UDXzVwWnn3mDy3mTpQPYb', 'spotify:album:3sW7wD2qdMjs7KncaOoIJ5', 'spotify:album:51h0awzHny8CZmIS6ECabP', 'spotify:album:0fuYENc2V5OhrMxu7VxRRr', 'spotify:album:023AUStvFJD8IzQqFeXRjB', 'spotify:album:0T23GvNaBUGtMKxZko8LQG', 'spotify:album:1Kw1bVd07oRqcjrcjQKC8T', 'spotify:album:2g1EakEaW7fPTZC6vBmBCn', 'spotify:album:3oQebIVUPY0IPiROZSIQFl']
['ANTI (Deluxe)', 'ANTI (Deluxe)', 'ANTI', 'ANTI', 'Unapologetic (Deluxe Version)', 'Unapologetic (Deluxe Version)', 'Unapologetic (Deluxe)', 'Unapologetic (Deluxe)', 'Unapologetic', 'Unapologetic', 'Unapologetic (Deluxe)', 'Unapologetic (Edited Version)', 'Talk That Talk (Deluxe)', 'Talk That Talk (Deluxe)', 'Unapologetic (Deluxe Version [Edited])', 'Unapologetic (Standard Version [Edited])', 'Unapologetic (Edited Version)', 'Talk That Talk', 'Talk That Talk', 'Talk That Talk (Deluxe Explicit)']

In [43]:
# 3 top albums

albums_3 = ['ANTI (Deluxe)','Unapologetic (Deluxe Version)','Talk That Talk (Deluxe)']
uris_3 = ['spotify:album:4UlGauD7ROb3YbVOFMgW5u','spotify:album:7yjQZX94GxVyqDTehxBejk', 'spotify:album:5UDXzVwWnn3mDy3mTpQPYb']
df_3 = {'albums': albums_3, 'uri':uris_3}

top_albums = pd.DataFrame(data=df_3, columns=["albums","uri"])
top_albums.insert(1, 'artist', 'Rihanna')
top_albums

,albums,artist,uri
0,ANTI (Deluxe),Rihanna,spotify:album:4UlGauD7ROb3YbVOFMgW5u
1,Unapologetic (Deluxe Version),Rihanna,spotify:album:7yjQZX94GxVyqDTehxBejk
2,Talk That Talk (Deluxe),Rihanna,spotify:album:5UDXzVwWnn3mDy3mTpQPYb

In [46]:

uris = 'spotify:album:4UlGauD7ROb3YbVOFMgW5u'
uri = []
name = []
track_number = []
disc_number = []


album_tracks = sp.album_tracks(uris)
df4 = pd.DataFrame(album_tracks)

for i, x in df4['items'].items():
  uri.append(x['uri'])
  name.append(x['name'])
  track_number.append(x['track_number'])
  disc_number.append(x['disc_number'])


df_unapologetic = pd.DataFrame({
'uri':uri,    
'name':name,
'track_number':track_number,
'disc_number':disc_number})

df_unapologetic.insert(1, 'artist', 'Rihanna')
df_unapologetic

,uri,artist,name,track_number,disc_number
0,spotify:track:6t90Z9XkdsHD8xMxro6KRP,Rihanna,Consideration,1,1
1,spotify:track:6K4Co1NQyOnoFEJMkZHkln,Rihanna,James Joint,2,1
2,spotify:track:0UHB9METy4VCXNgkcGqHqS,Rihanna,Kiss It Better,3,1
3,spotify:track:72TFWvU3wUYdUuxejTTIzt,Rihanna,Work,4,1
4,spotify:track:4mCf3vQf7z0Yseo0RxAi3V,Rihanna,Desperado,5,1
5,spotify:track:3HQcsqRjRdruUjkbDSgmVF,Rihanna,Woo,6,1
6,spotify:track:4pAl7FkDMNBsjykPXo91B3,Rihanna,Needed Me,7,1
7,spotify:track:7eDYNlBwRMeFOZHOZ95dZ1,Rihanna,"Yeah, I Said It",8,1
8,spotify:track:6RtzmszGXs32TRhv5zTKNM,Rihanna,Same Ol’ Mistakes,9,1
9,spotify:track:7Jd5LgnSRQElW6FsTWVPzE,Rihanna,Never Ending,10,1
10,spotify:track:5oO3drDxtziYU2H1X23ZIp,Rihanna,Love On The Brain,11,1
11,spotify:track:1KnJwhZU3DIBe54Q4HPpIl,Rihanna,Higher,12,1
12,spotify:track:6D2tzc8kRnZb7P1lNwMBLH,Rihanna,Close To You,13,1
13,spotify:track:5LJz7kmFhLqB53tmVWxig5,Rihanna,Goodnight Gotham,14,1
14,spotify:track:4UTizOdGljPIIbXtoXycAd,Rihanna,Pose,15,1
15,spotify:track:7BiELrM90hRxpozaIXbsLw,Rihanna,Sex With Me,16,1

In [48]:
#Put for the user to input the album uri

uris = 'spotify:album:7yjQZX94GxVyqDTehxBejk'
uri = []
name = []
track_number = []
disc_number = []


album_tracks = sp.album_tracks(uris)
df5 = pd.DataFrame(album_tracks)

for i, x in df5['items'].items():
  uri.append(x['uri'])
  name.append(x['name'])
  track_number.append(x['track_number'])
  disc_number.append(x['disc_number'])


df_anti = pd.DataFrame({
'uri':uri,    
'name':name,
'track_number':track_number,
'disc_number':disc_number})

df_anti.insert(1, 'artist', 'Rihanna')
df_anti

,uri,artist,name,track_number,disc_number
0,spotify:track:6bqOolsv57aEE8Q3PixC7p,Rihanna,Phresh Out The Runway,1,1
1,spotify:track:1kde2QG8s4pbZDiI8Fklzq,Rihanna,Diamonds,2,1
2,spotify:track:0zeXzdgaRKs2TiUYxNGDD0,Rihanna,Numb,3,1
3,spotify:track:11gr64dfNTZ179JQICaRIc,Rihanna,Pour It Up,4,1
4,spotify:track:4GIopCOy1bhVqVfAMiM81L,Rihanna,Loveeeeeee Song,5,1
5,spotify:track:1fAQcrmQEPhAUfx9tzVfQ1,Rihanna,Jump,6,1
6,spotify:track:2lcsukpwDNXQu73W1IQfLr,Rihanna,Right Now,7,1
7,spotify:track:5kgcqk2xzjHmB3GmO3yKmz,Rihanna,What Now,8,1
8,spotify:track:4qaEPJ1S3GkITZRzuNgiwQ,Rihanna,Stay,9,1
9,spotify:track:16DOpNAr7bGZlMJvjVf5Ra,Rihanna,Nobody's Business,10,1
10,spotify:track:477aE6KFSka7QOZDrZ9NVe,Rihanna,Love Without Tragedy / Mother Mary,11,1
11,spotify:track:4KW3pEgOpXAzJLih3cAfK7,Rihanna,Get It Over With,12,1
12,spotify:track:5UsBzWkwj4Hp3sQmKHAiGt,Rihanna,No Love Allowed,13,1
13,spotify:track:5l6AmqCEZqYT0BQcEB3SEy,Rihanna,Lost In Paradise,14,1
14,spotify:track:3JmvdozLe9TNpLGeCCghD2,Rihanna,Half Of Me,15,1
15,spotify:track:0lqjeOKyWb4s9nvDlF68Ov,Rihanna,Diamonds,16,1
16,spotify:track:14jjgYw4kKsexFJ1NtkMO7,Rihanna,Diamonds,17,1

In [49]:
uris = 'spotify:album:5UDXzVwWnn3mDy3mTpQPYb'
uri = []
name = []
track_number = []
disc_number = []


album_tracks = sp.album_tracks(uris)
df6 = pd.DataFrame(album_tracks)

for i, x in df6['items'].items():
  uri.append(x['uri'])
  name.append(x['name'])
  track_number.append(x['track_number'])
  disc_number.append(x['disc_number'])


df_talk = pd.DataFrame({
'uri':uri,    
'name':name,
'track_number':track_number,
'disc_number':disc_number})

df_talk.insert(1, 'artist', 'Rihanna')
df_talk

,uri,artist,name,track_number,disc_number
0,spotify:track:5C3XPfy7OSXHpclNc6UfN8,Rihanna,Phresh Out The Runway - Album Version (Edited),1,1
1,spotify:track:7i0jaBLpIADxqNbhAb4XFb,Rihanna,Diamonds,2,1
2,spotify:track:3gkigp03NzQ3eHB39uwW6F,Rihanna,Numb - Album Version (Edited),3,1
3,spotify:track:2gtYsdzVF47HhN61NaULAv,Rihanna,Pour It Up - Album Version (Edited),4,1
4,spotify:track:7fSg2bktX4zvkY6VpArJJK,Rihanna,Loveeeeeee Song - Album Version (Edited),5,1
5,spotify:track:3qVmMSEuMYCPdUVNrapUG9,Rihanna,Jump - Album Version (Edited),6,1
6,spotify:track:2jrJmE5g5YjgBj66As4Wgg,Rihanna,Right Now - Album Version (Edited),7,1
7,spotify:track:2Nm9ozosnDBfXRLOgMCNd2,Rihanna,What Now - Album Version (Edited),8,1
8,spotify:track:2Yy0FsAV2I5VXU4xpph2WN,Rihanna,Stay - Album Version (Edited),9,1
9,spotify:track:1nU9uMV52uwVjlh1vPE7MI,Rihanna,Nobody's Business - Album Version (Edited),10,1
10,spotify:track:72mdt7PXj2TGTIKaNNeKuX,Rihanna,Love Without Tragedy / Mother Mary - Album Ver...,11,1
11,spotify:track:2YQDSkzHLnJSuqNZMqr4Hz,Rihanna,Get It Over With - Album Version (Edited),12,1
12,spotify:track:4OfY1ClwqlDiQsRI3IdL30,Rihanna,No Love Allowed - Album Version (Edited),13,1
13,spotify:track:751YV4A25c5gXdXkBptKNg,Rihanna,Lost In Paradise - Album Version (Edited),14,1

In [53]:
# Get the top tracks' informations
uri = df2['track_id']

def getTopTrackFeatures(uri):
  song = sp.track(uri)
  song_features = sp.audio_features(uri)

  name = song['name']
  album = song['album']['name']
  artist = song['album']['artists'][0]['name']

  # features
  acousticness = song_features[0]['acousticness']
  danceability = song_features[0]['danceability']
  energy = song_features[0]['energy']
  duration = song_features[0]['duration_ms']

  track = [name, album, artist, acousticness, danceability, energy, duration]
  return track

In [54]:
tracks = []

for i in range(len(uri)):
  track = getTopTrackFeatures(uri[i])
  tracks.append(track)

# create dataset
df_tracks = pd.DataFrame(tracks, columns = ['name', 'album', 'artist', 'acousticness', 'danceability', 'energy', 'duration'])
df_tracks

,name,album,artist,acousticness,danceability,energy,duration
0,Umbrella,Good Girl Gone Bad,Rihanna,0.00864,0.583,0.829,275987
1,Love On The Brain,ANTI (Deluxe),Rihanna,0.07170,0.509,0.637,224000
2,This Is What You Came For,This Is What You Came For,Calvin Harris,0.19900,0.631,0.927,222160
3,Needed Me,ANTI (Deluxe),Rihanna,0.11000,0.671,0.314,191600
4,Don't Stop The Music,Good Girl Gone Bad,Rihanna,0.03360,0.835,0.669,267080
5,Woo,ANTI (Deluxe),Rihanna,0.05460,0.420,0.466,235587
6,Only Girl (In The World),Loud (Japan Version),Rihanna,0.11200,0.789,0.706,235493
7,We Found Love,Talk That Talk,Rihanna,0.02500,0.734,0.766,215227
8,Disturbia,Good Girl Gone Bad: Reloaded,Rihanna,0.08630,0.707,0.813,238627
9,FourFiveSeconds,FourFiveSeconds,Rihanna,0.87500,0.582,0.272,188238

In [ ]:
from sqlalchemy import create_engine
import psycopg2 

conn_string = 'postgresql://{user}:{password}@localhost:5433/{database}'

final = df_tracks

db = create_engine(conn_string)
conn = db.connect()

final.to_sql('data', con=conn, if_exists='replace', index=False)
conn = psycopg2.connect(conn_string)
conn.autocommit = True
cursor = conn.cursor()
sqll = '''select * from data; '''
cursor.execute(sqll)
for i in cursor.fetchall():
    print(i)

#close connection
conn.close()